<?php

/**
 * @file
 * Contains h22_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function h22_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the h22_core module.
    case 'help.page.h22_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core module, required by the project.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function h22_core_theme() {
  return [
    'h22_core_homepage' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function h22_core_form_node_host_location_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Get only configurable languages in content language selector.
  $new_language_options = [];
  $languages = \Drupal::languageManager()->getLanguages();
  foreach ($languages as $langcode => $language) {
    /** @var \Drupal\Core\StringTranslation\TranslatableMarkup $language */
    $new_language_options[$langcode] = $language->getName();
  }
  $form["langcode"]["widget"][0]["value"]["#options"] = $new_language_options;

  // Hide author options if authenticated user.
  $current_user = \Drupal::currentUser();
  $user_roles = $current_user->getRoles();
  if (in_array('authenticated', $user_roles) && !in_array('administrator', $user_roles)) {
    $form['revision_log']['#access'] = FALSE;
    $form['meta']['#access'] = FALSE;
    $form['meta']['published']['#access'] = FALSE;
    $form['meta']['changed']['#access'] = FALSE;
    $form['meta']['author']['#access'] = FALSE;
  }

  // Add HTML help text field.
  $form['meta']['host_location_help'] = [
    '#type' => 'item',
    '#markup' => t('If you are willing and capable to host refugees, please submit your details so refugees can contact you.'),
    '#wrapper_attributes' => ['class' => ['host_location_help']],
    '#weight' => '0',
  ];

  $form['meta']['host_location_warning'] = [
    '#type' => 'item',
    '#title' => t('Warning'),
    '#wrapper_attributes' => ['class' => ['host_location_warning']],
    '#markup' =>
    t('As it is now wartime, please be wary of sabotage and Russian hacks.<br>
      We are taking all the safety measures to protect your data and your identity.<br><br>

      To help us take these measures:
      <ul>
        <li>Do not share your precise home address.</li>
        <li>Talk to the person before accepting to host.</li>
      </ul>
      <br>
      Follow the general safety measures to assure your and refugees safety.'),
    '#weight' => '0',
  ];
}
